services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=${ENV_POSTGRES_HOST}
      - POSTGRES_DB=${ENV_POSTGRES_DEV_DB}
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
      - MICROSOFT_GRAPH_CLIENT_ID=${MICROSOFT_GRAPH_CLIENT_ID}
      - MICROSOFT_GRAPH_CLIENT_SECRET=${MICROSOFT_GRAPH_CLIENT_SECRET}
      - MICROSOFT_GRAPH_TENANT_ID=${MICROSOFT_GRAPH_TENANT_ID}
      - AGATHA_USE_MICROSOFT_GRAPH=${AGATHA_USE_MICROSOFT_GRAPH}
      - AGATHA_ENABLE_DEBUG_LOGGING=${AGATHA_ENABLE_DEBUG_LOGGING:-true}  
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Bind mount for live reload
    # Remove the command override
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${ENV_POSTGRES_DEV_DB}
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/robert/agathabackup/:/backups
    ports:
      - "5432:5432"

volumes:
  postgres_data: